[programs.localnet]
sollar_protocol = "GGctambdwXbK5VnbLkyR9xfn3gvJgZVE4yfxQVCkkh5t"
psy_american = "HKsX4fwmkR6LeFXhjAVRAEAddRi1mKu8CdVJMQHg8Yo5"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/guanzhi2/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
